sports-split-default: &default
    early_stop_patience: 1
    batch_norm: true
    batch_size: 8192
    # batch_size: 1024
    debug_mode: false
    dnn_activations: relu
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 100
    eval_interval: 1
    # learning_rate: 0.00001
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 128
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./checkpoints/run/
    model_structure: parallel
    monitor: {AUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    # num_cross_layers: 2
    num_experts: 2
    num_workers: 16
    optimizer: adam
    # parallel_dnn_hidden_units: [256, 256]
    # parallel_dnn_hidden_units: [512, 256, 128, 64]
    parallel_dnn_hidden_units: [512, 256, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2333
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_low_rank_mixture: false
    verbose: 1
  
sports-split-ui:
    <<: *default
    dataset_id: sports-split-ui
  
sports-split:
    <<: *default
    dataset_id: sports-split 

# moe
sports-split-moe-1:
    <<: *default
    dataset_id: sports-split-moe-1

sports-split-moe-2:
    <<: *default
    dataset_id: sports-split-moe-2

sports-split-moe-3:
    <<: *default
    dataset_id: sports-split-moe-3

sports-split-moe-4:
    <<: *default
    dataset_id: sports-split-moe-4

sports-split-moe-5:
    <<: *default
    dataset_id: sports-split-moe-5

sports-split-moe-6:
    <<: *default
    dataset_id: sports-split-moe-6

sports-split-moe-7:
    <<: *default
    dataset_id: sports-split-moe-7

# noise
sports-split-moe-1-noise:
    <<: *default
    dataset_id: sports-split-moe-1-noise

sports-split-moe-2-noise:
    <<: *default
    dataset_id: sports-split-moe-2-noise

sports-split-moe-3-noise:
    <<: *default
    dataset_id: sports-split-moe-3-noise

sports-split-moe-4-noise:
    <<: *default
    dataset_id: sports-split-moe-4-noise

sports-split-moe-5-noise:
    <<: *default
    dataset_id: sports-split-moe-5-noise

sports-split-moe-6-noise:
    <<: *default
    dataset_id: sports-split-moe-6-noise

sports-split-moe-7-noise:
    <<: *default
    dataset_id: sports-split-moe-7-noise


# rq
sports-split-rq-1:
    <<: *default
    dataset_id: sports-split-rq-1

sports-split-rq-2:
    <<: *default
    dataset_id: sports-split-rq-2

sports-split-rq-3:
    <<: *default
    dataset_id: sports-split-rq-3

sports-split-rq-4:
    <<: *default
    dataset_id: sports-split-rq-4

sports-split-rq-5:
    <<: *default
    dataset_id: sports-split-rq-5

sports-split-rq-6:
    <<: *default
    dataset_id: sports-split-rq-6

sports-split-rq-7:
    <<: *default
    dataset_id: sports-split-rq-7


# seq
sports-split-rq-1-seq:
    <<: *default
    dataset_id: sports-split-rq-1-seq

sports-split-rq-2-seq:
    <<: *default
    dataset_id: sports-split-rq-2-seq

sports-split-rq-3-seq:
    <<: *default
    dataset_id: sports-split-rq-3-seq

sports-split-rq-4-seq:
    <<: *default
    dataset_id: sports-split-rq-4-seq

sports-split-rq-5-seq:
    <<: *default
    dataset_id: sports-split-rq-5-seq

sports-split-rq-6-seq:
    <<: *default
    dataset_id: sports-split-rq-6-seq

sports-split-rq-7-seq:
    <<: *default
    dataset_id: sports-split-rq-7-seq

# uni
sports-split-rq-1-uni:
    <<: *default
    dataset_id: sports-split-rq-1-uni

sports-split-rq-2-uni:
    <<: *default
    dataset_id: sports-split-rq-2-uni

sports-split-rq-3-uni:
    <<: *default
    dataset_id: sports-split-rq-3-uni

sports-split-rq-4-uni:
    <<: *default
    dataset_id: sports-split-rq-4-uni

sports-split-rq-5-uni:
    <<: *default
    dataset_id: sports-split-rq-5-uni

sports-split-rq-6-uni:
    <<: *default
    dataset_id: sports-split-rq-6-uni

sports-split-rq-7-uni:
    <<: *default
    dataset_id: sports-split-rq-7-uni


# moe-seq
sports-split-moe-1-seq:
    <<: *default
    dataset_id: sports-split-moe-1-seq

sports-split-moe-2-seq:
    <<: *default
    dataset_id: sports-split-moe-2-seq

sports-split-moe-3-seq:
    <<: *default
    dataset_id: sports-split-moe-3-seq

sports-split-moe-4-seq:
    <<: *default
    dataset_id: sports-split-moe-4-seq

sports-split-moe-5-seq:
    <<: *default
    dataset_id: sports-split-moe-5-seq

sports-split-moe-6-seq:
    <<: *default
    dataset_id: sports-split-moe-6-seq

sports-split-moe-7-seq:
    <<: *default
    dataset_id: sports-split-moe-7-seq


# moe-uni
sports-split-moe-1-uni:
    <<: *default
    dataset_id: sports-split-moe-1-uni

sports-split-moe-2-uni:
    <<: *default
    dataset_id: sports-split-moe-2-uni

sports-split-moe-3-uni:
    <<: *default
    dataset_id: sports-split-moe-3-uni

sports-split-moe-4-uni:
    <<: *default
    dataset_id: sports-split-moe-4-uni

sports-split-moe-5-uni:
    <<: *default
    dataset_id: sports-split-moe-5-uni

sports-split-moe-6-uni:
    <<: *default
    dataset_id: sports-split-moe-6-uni

sports-split-moe-7-uni:
    <<: *default
    dataset_id: sports-split-moe-7-uni

# me
sports-split-me-1:
    <<: *default
    dataset_id: sports-split-me-1

sports-split-me-2:
    <<: *default
    dataset_id: sports-split-me-2

sports-split-me-3:
    <<: *default
    dataset_id: sports-split-me-3

sports-split-me-4:
    <<: *default
    dataset_id: sports-split-me-4

sports-split-me-5:
    <<: *default
    dataset_id: sports-split-me-5

sports-split-me-6:
    <<: *default
    dataset_id: sports-split-me-6

sports-split-me-7:
    <<: *default
    dataset_id: sports-split-me-7